# jwt configuration
jwt:
  signing-key: 'beeAdmin'

# mysql connect configuration
mysql:
  username: root
  password: 'Li763a7689'
  path: '121.89.167.190:3306'
  db-name: 'bee'
  config: 'charset=utf8&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true
